version: "3"

services:
  jekyll:
    image: jekyll/jekyll
    command: bash -c "bundle install && jekyll serve --livereload --watch" # --force_polling
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
        - .:/srv/jekyll
