version: "3"

services:
  jekyll:
      image: jekyll/jekyll:builder
      command: bash -c "bundle install && bundle exec jekyll serve --watch --force_polling --host 0.0.0.0"
      ports:
          - 127.0.0.1:4000:4000
      volumes:
          - .:/srv/jekyll