version: "3"

services:
  jekyll:
      image: jekyll/jekyll:builder
      command: jekyll serve --watch --force_polling
      ports:
          - 127.0.0.1:4000:4000
      volumes:
          - .:/srv/jekyll